pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/abhinavakr/Docker-Zero-to-Heroabhi/tree/main/examples/first-docker-file.git', branch: 'main'
            }
        }
        
        stage('Build') {
            steps {
                script {
                    docker.build('my-python-app')
                }
            }
        }
        
        stage('Test') {
            steps {
                script {
                    docker.image('my-python-app').inside {
                        sh 'python app.py test'
                    }
                }
            }
        }
        
        stage('Deploy') {
            steps {
                script {
                    docker.image('my-python-app').inside {
                        sh 'python app.py'
                    }
                }
            }
        }
    }
}

               
